"""Interactive first-run wizard — built for Termux keyboards."""

from __future__ import annotations

import getpass
import os
import sys
from app.config import LIVE_CONFIRM_PHRASE, ROOT, get_settings, reload_env
from app.llm import PROVIDERS

ENV_PATH = ROOT / ".env"


def _ask(prompt: str, default: str = "", secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    label = f"{prompt}{suffix}: "
    if secret:
        raw = getpass.getpass(label)
    else:
        try:
            raw = input(label)
        except EOFError:
            raw = ""
    raw = (raw or "").strip()
    return raw or default


def _write_env(values: dict[str, str]) -> None:
    existing: dict[str, str] = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            if not line or line.lstrip().startswith("#") or "=" not in line:
                continue
            key, val = line.split("=", 1)
            existing[key.strip()] = val
    existing.update(values)
    lines = [
        "# Generated by `python -m app setup`. Do not commit this file.",
        f"TRADING_MODE={existing.get('TRADING_MODE', 'paper')}",
        f"PAPER_STARTING_CASH={existing.get('PAPER_STARTING_CASH', '10')}",
        f"STAKE_USD={existing.get('STAKE_USD', '10')}",
        f"GOAL_USD={existing.get('GOAL_USD', '50')}",
        f"MIN_NOTIONAL={existing.get('MIN_NOTIONAL', '5')}",
        f"PROFIT_MODE={existing.get('PROFIT_MODE', 'true')}",
        f"MANAGE_SECONDS={existing.get('MANAGE_SECONDS', '60')}",
        f"TRAIL_ATR={existing.get('TRAIL_ATR', '1.8')}",
        f"BINANCE_API_KEY={existing.get('BINANCE_API_KEY', '')}",
        f"BINANCE_API_SECRET={existing.get('BINANCE_API_SECRET', '')}",
        f"BINANCE_LIVE_CONFIRM={existing.get('BINANCE_LIVE_CONFIRM', '')}",
        f"LLM_PROVIDER={existing.get('LLM_PROVIDER', '')}",
        f"LLM_MODEL={existing.get('LLM_MODEL', '')}",
        f"LLM_BASE_URL={existing.get('LLM_BASE_URL', '')}",
        f"TRADINGAGENTS_LLM_PROVIDER={existing.get('TRADINGAGENTS_LLM_PROVIDER', existing.get('LLM_PROVIDER', ''))}",
        f"TRADINGAGENTS_DEEP_THINK_MODEL={existing.get('TRADINGAGENTS_DEEP_THINK_MODEL', '')}",
        f"TRADINGAGENTS_QUICK_THINK_MODEL={existing.get('TRADINGAGENTS_QUICK_THINK_MODEL', '')}",
        f"TRADINGAGENTS_MAX_DEBATE_ROUNDS={existing.get('TRADINGAGENTS_MAX_DEBATE_ROUNDS', '1')}",
    ]
    for spec in PROVIDERS.values():
        env = spec["env"]
        lines.append(f"{env}={existing.get(env, '')}")
    lines.extend(
        [
            f"WATCHLIST={existing.get('WATCHLIST', 'BTCUSDT,ETHUSDT,SOLUSDT')}",
            f"INTERVAL={existing.get('INTERVAL', '1h')}",
            f"LOOP_SECONDS={existing.get('LOOP_SECONDS', '900')}",
            f"MIN_CONFIDENCE={existing.get('MIN_CONFIDENCE', '0.58')}",
            f"MAX_POSITIONS={existing.get('MAX_POSITIONS', '1')}",
            f"MAX_DAILY_LOSS_PCT={existing.get('MAX_DAILY_LOSS_PCT', '15')}",
            f"COOLDOWN_MINUTES={existing.get('COOLDOWN_MINUTES', '20')}",
            f"AUTO_EXECUTE={existing.get('AUTO_EXECUTE', 'true')}",
            f"HOST={existing.get('HOST', '0.0.0.0')}",
            f"PORT={existing.get('PORT', '8000')}",
        ]
    )
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(ENV_PATH, 0o600)
    except OSError:
        pass


def run_setup(*, start: bool = False) -> None:
    print()
    print("LOLMUTR  ·  Termux / headless desk")
    print("Not financial advice. Paper is the default. Live needs an extra phrase.")
    print("Stake mode compounds a small book toward a goal (default $10 → $50).")
    print()

    stake = _ask("Starting stake USD", "10")
    goal = _ask("Goal USD (lock the book when hit)", "50")
    values: dict[str, str] = {
        "STAKE_USD": stake,
        "GOAL_USD": goal,
        "PAPER_STARTING_CASH": stake,
        "MAX_POSITIONS": "1",
    }

    providers = "/".join(["nvidia", "none", *[p for p in PROVIDERS if p != "nvidia"]])
    provider = _ask(f"LLM provider ({providers})", "nvidia").lower()
    if provider in PROVIDERS:
        values["LLM_PROVIDER"] = provider
        key = _ask(f"{PROVIDERS[provider]['env']}", secret=True)
        if not key:
            print("No LLM key — TradingAgents stays offline and the book stays flat.")
        else:
            values[PROVIDERS[provider]["env"]] = key
        model = _ask("Model (enter for default)", PROVIDERS[provider]["model"])
        values["LLM_MODEL"] = model
        if provider == "nvidia":
            values["LLM_BASE_URL"] = "https://integrate.api.nvidia.com/v1"
            values["TRADINGAGENTS_LLM_PROVIDER"] = "openai_compatible"
            values["TRADINGAGENTS_LLM_BACKEND_URL"] = "https://integrate.api.nvidia.com/v1"
            values["TRADINGAGENTS_DEEP_THINK_MODEL"] = model
            values["TRADINGAGENTS_QUICK_THINK_MODEL"] = model
    else:
        values["LLM_PROVIDER"] = ""

    mode = _ask("Trading mode (paper/testnet/live)", "paper").lower()
    if mode not in {"paper", "testnet", "live"}:
        mode = "paper"
    values["TRADING_MODE"] = mode

    print()
    print("Binance API keys (spot read). Needed to talk to your account.")
    values["BINANCE_API_KEY"] = _ask("BINANCE_API_KEY", secret=True)
    values["BINANCE_API_SECRET"] = _ask("BINANCE_API_SECRET", secret=True)
    if mode == "live":
        print()
        print("LIVE sends real market orders. Type the exact phrase to unlock.")
        confirm = _ask(f"Type {LIVE_CONFIRM_PHRASE} to unlock live")
        values["BINANCE_LIVE_CONFIRM"] = confirm
        if confirm != LIVE_CONFIRM_PHRASE:
            print("Phrase did not match — forcing paper mode.")
            values["TRADING_MODE"] = "paper"
            values["BINANCE_LIVE_CONFIRM"] = ""

    values["WATCHLIST"] = _ask("Watchlist", "BTCUSDT,ETHUSDT,SOLUSDT")
    minutes = _ask("Minutes between loops", "15")
    try:
        values["LOOP_SECONDS"] = str(max(60, int(float(minutes) * 60)))
    except ValueError:
        values["LOOP_SECONDS"] = "900"
    values["INTERVAL"] = _ask("Kline interval", "1h")
    auto = _ask("Auto-execute tickets? (Y/n)", "Y").lower()
    values["AUTO_EXECUTE"] = "false" if auto in {"n", "no"} else "true"

    _write_env(values)
    reload_env()
    settings = get_settings()
    from app.binance.probe import probe

    print()
    print("Checking Binance…")
    result = probe(
        settings.binance_api_key,
        settings.binance_api_secret,
        testnet=settings.trading_mode == "testnet",
    )
    print("  public :", "OK" if result["public_ok"] else "FAIL", result.get("public_host") or "")
    print("  keys   :", "OK" if result["signed_ok"] else "FAIL", result.get("signed_detail"))
    if settings.binance_api_key and not result["signed_ok"]:
        print("  hint   : enable Spot, turn off IP restriction or add this phone IP,")
        print("           use api.binance.com keys (not binance.us), check secret.")
    # Fresh paper book at the new stake so an old $10k file does not linger.
    from app.binance.paper import PaperBroker

    PaperBroker(starting_cash=settings.paper_starting_cash).reset()
    print()
    print(f"Wrote {ENV_PATH}")
    print(
        f"mode={settings.trading_mode}  execute={settings.auto_execute}  "
        f"watchlist={','.join(settings.watchlist)}  llm={settings.llm_provider or 'none'}"
    )
    print()

    if not start:
        go = _ask("Start autotrader now? (Y/n)", "Y").lower()
        start = go not in {"n", "no"}
    if start:
        from app.cockpit import run_cockpit

        run_cockpit()
    else:
        print("Start later with:  python -m app trade")
